name: build

on: [push, pull_request]

jobs:
  test:
    name: Test PHP ${{ matrix.php-version }} with Code Coverage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
    steps:
      - name: Install ODBC driver.
        run: |
          sudo curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup DB services
        run: |
          cd tests
          docker compose up -d
          cd ..
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          tools: pecl
          extensions: mbstring, pdo, pdo_sqlite, pdo_pgsql, pdo_sqlsrv-5.11, pdo_mysql

      - name: Install dependencies with composer
        uses: ramsey/composer-install@v3

      - name: Execute Tests
        run: |
          vendor/bin/phpunit --coverage-clover=coverage.clover

      - name: Upload coverage to Codecov
        continue-on-error: true # if is fork
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.clover

      - name: Upload coverage to Scrutinizer
        continue-on-error: true # if is fork
        uses: sudo-bot/action-scrutinizer@latest
        with:
          cli-args: "--format=php-clover coverage.clover"
